-- MySQL Script generated by MySQL Workbench
-- 06/29/14 22:03:07
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zqccms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zqccms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `zqccms` ;

-- -----------------------------------------------------
-- Table `zqccms`.`zqc_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zqccms`.`zqc_model` (
  `model_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '模型ID',
  `model_name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '模型名称',
  `model_table` TEXT NOT NULL DEFAULT '' COMMENT '附加表名称',
  PRIMARY KEY (`model_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zqccms`.`zqc_column`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zqccms`.`zqc_column` (
  `column_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '栏目ID',
  `sid` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT '排序ID',
  `cid` INT UNSIGNED NOT NULL DEFAULT '' COMMENT '所属栏目ID',
  `column_name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '栏目名字',
  `column_content` TEXT NOT NULL DEFAULT '' COMMENT '栏目类容',
  `mid` INT UNSIGNED NOT NULL DEFAULT '' COMMENT '所属模型ID',
  PRIMARY KEY (`column_id`),
  INDEX `fk_zqc_column_zqc_model_idx` (`mid` ASC),
  CONSTRAINT `fk_zqc_column_zqc_model`
    FOREIGN KEY (`mid`)
    REFERENCES `zqccms`.`zqc_model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zqccms`.`zqc_modelnews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zqccms`.`zqc_modelnews` (
  `news_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `news_title` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '新闻标题',
  `news_intro` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '新闻简介',
  `news_writer` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '发表作者',
  `news_time` INT(11) UNSIGNED NOT NULL DEFAULT '' COMMENT '发表时间',
  `news_click` INT UNSIGNED NOT NULL DEFAULT '' COMMENT '点击次数',
  `news_image` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '新闻图片',
  `news_text` TEXT NOT NULL DEFAULT '' COMMENT '新闻内容',
  `cid` INT UNSIGNED NOT NULL DEFAULT '' COMMENT '所属栏目',
  `mid` INT UNSIGNED NOT NULL DEFAULT '' COMMENT '所属模型',
  PRIMARY KEY (`news_id`),
  INDEX `fk_zqc_modelnews_zqc_column1_idx` (`cid` ASC),
  INDEX `fk_zqc_modelnews_zqc_model1_idx` (`mid` ASC),
  CONSTRAINT `fk_zqc_modelnews_zqc_column1`
    FOREIGN KEY (`cid`)
    REFERENCES `zqccms`.`zqc_column` (`column_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zqc_modelnews_zqc_model1`
    FOREIGN KEY (`mid`)
    REFERENCES `zqccms`.`zqc_model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zqccms`.`zqc_carousel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zqccms`.`zqc_carousel` (
  `carousel_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '轮播图片ID',
  `carousel_photo` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '图片地址',
  `carousel_content` TEXT NOT NULL DEFAULT '' COMMENT '图片说明',
  `cid` INT UNSIGNED NOT NULL DEFAULT '' COMMENT '所属栏目',
  PRIMARY KEY (`carousel_id`),
  INDEX `fk_zqc_carousel_zqc_column1_idx` (`cid` ASC),
  CONSTRAINT `fk_zqc_carousel_zqc_column1`
    FOREIGN KEY (`cid`)
    REFERENCES `zqccms`.`zqc_column` (`column_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zqccms`.`zqc_entirety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zqccms`.`zqc_entirety` (
  `entirety_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '整体布局ID',
  `entirety_title` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '网站标题',
  `entirety_keywords` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '网站关键字',
  `entirety_description` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '网站描述',
  `entirety_logo` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '网站LOGO',
  `entirety_content` DATETIME NOT NULL DEFAULT '' COMMENT '网站底部信息',
  PRIMARY KEY (`entirety_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
